/*
 * pids_supported.h
 *
 *  Created on: Nov 15, 2020
 *      Author: Matth
 */

#ifndef PIDS_SUPPORTED_H_
#define PIDS_SUPPORTED_H_

#define MODE1_CALCULATED_ENGINE_LOAD_SUPPORTED
#define MODE1_ENGINE_COOLANT_TEMPERATURE_SUPPORTED
#define MODE1_FUEL_PRESSURE_SUPPORTED
#define MODE1_INTAKE_MANIFOLD_ABSOLUTE_PRESSURE_SUPPORTED
#define MODE1_ENGINE_SPEED_SUPPORTED
#define MODE1_VEHICLE_SPEED_SUPPORTED
#define MODE1_TIMING_ADVANCE_SUPPORTED
#define MODE1_INTAKE_AIR_TEMPERATURE_SUPPORTED
#define MODE1_MAF_AIR_FLOW_RATE_SUPPORTED
#define MODE1_AMBIENT_AIR_TEMPERATURE_SUPPORTED
#define MODE1_BAROMETRIC_PRESSURE_SUPPORTED
#define MODE1_ABSOLUTE_BAROMETRIC_PRESSURE_SUPPORTED
#define MODE1_THROTTLE_POSITION_SUPPORTED
#define MODE1_RELATIVE_ACCELERATOR_PEDAL_POSITION_SUPPORTED
#define MODE1_ENGINE_OIL_TEMPERATURE_SUPPORTED
#define MODE1_TURBOCHARGER_COMPRESSOR_INLET_PRESSURE_SUPPORTED
#define MODE1_TRANS_ACTUAL_GEAR_SUPPORTED
#define MODE22_INTAKE_AIR_TEMPERATURE_SUPPORTED
#define MODE22_CHARGE_AIR_TEMPERATURE_SUPPORTED
#define MODE22_AMBIENT_AIR_TEMPERATURE_SUPPORTED
#define SNIFF_GAUGE_BRIGHTNESS_SUPPORTED
#define SNIFF_CLUTCH_POSITION_SUPPORTED

#endif /* PIDS_SUPPORTED_H_ */
