/*
 * pids_supported.h
 *
 *  Created on: Nov 15, 2020
 *      Author: Matth
 */

#ifndef PIDS_SUPPORTED_H_
#define PIDS_SUPPORTED_H_

#define MODE1_CALCULATED_ENGINE_LOAD_VALUE_SUPPORTED
#define MODE1_ENGINE_COOLANT_TEMPERATURE_SUPPORTED
#define MODE1_FUEL_PRESSURE_SUPPORTED
#define MODE1_INTAKE_MANIFOLD_ABSOLUTE_PRESSURE_SUPPORTED
#define MODE1_ENGINE_RPM_SUPPORTED
#define MODE1_VEHICLE_SPEED_SUPPORTED
#define MODE1_TIMING_ADVANCE_SUPPORTED
#define MODE1_INTAKE_AIR_TEMPERATURE_SUPPORTED
#define MODE1_MAF_AIR_FLOW_RATE_SUPPORTED
#define MODE1_AMBIENT_AIR_TEMPERATURE_SUPPORTED
#define MODE1_BAROMETRIC_PRESSURE_SUPPORTED
#define MODE1_ABSOLUTE_LOAD_VALUE_SUPPORTED
#define MODE1_THROTTLE_POSITION_SUPPORTED
#define MODE1_REL_ACCELERATOR_PEDAL_POS_SUPPORTED
#define MODE1_ENGINE_OIL_TEMPERATURE_SUPPORTED
#define MODE1_TURBO_INLET_PRESSURE_SUPPORTED
#define MODE1_TRANS_ACTUAL_GEAR_SUPPORTED
#define MODE22_INTAKE_AIR_TEMPERATURE_SUPPORTED
#define MODE22_CHARGE_AIR_TEMPERATURE_SUPPORTED
#define DECODE_GAUGE_BRIGHTNESS_SUPPORTED
#define DECODE_CLUTCH_POSITION_SUPPORTED

#endif /* PIDS_SUPPORTED_H_ */
